name: Deploy Sahajanand-BE

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'server.ts'

env:
  CI: false

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    name: Deploy sahajanand-Backend to Dev
    if: ${{ github.ref == 'refs/heads/dev' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH for BE
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 82.29.160.246 >> ~/.ssh/known_hosts

    - name: Test SSH Connection for BE
      run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@82.29.160.246 "echo 'SSH connection successful!'"

    - name: Deploy sahajanand-Backend changes to Dev via SSH
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@82.29.160.246 << 'EOF'
          set -e
          echo "Starting deployment to dev environment..."
          
          cd /home/ubuntu/sahajanand/dev/sahajanand-Backend
          echo "Current directory: $(pwd)"
          
          echo "Pulling latest changes from dev branch..."
          git pull origin dev
          
          echo "Installing dependencies..."
          npm install
          
          echo "Building the application..."
          npm run build
          
          echo "Restarting PM2 process..."
          pm2 restart sahajanand-BE-dev
          
          echo "Checking PM2 status..."
          pm2 status
          
          echo "Deployment to dev completed successfully!"
        EOF

  deploy-to-main:
    runs-on: ubuntu-latest
    name: Deploy sahajanand-Backend to Main
    if: ${{ github.ref == 'refs/heads/main' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH for BE
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 82.29.160.246 >> ~/.ssh/known_hosts

    - name: Test SSH Connection for BE
      run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@82.29.160.246 "echo 'SSH connection successful!'"

    - name: Deploy sahajanand-Backend changes to Main via SSH
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@82.29.160.246 << 'EOF'
          set -e
          echo "Starting deployment to main environment..."
          
          cd /home/ubuntu/sahajanand/live/sahajanand-Backend
          echo "Current directory: $(pwd)"
          
          echo "Pulling latest changes from main branch..."
          git pull origin main
          
          echo "Installing dependencies..."
          npm install
          
          echo "Building the application..."
          npm run build
          
          echo "Restarting PM2 process..."
          pm2 restart sahajanand-BE-live
          
          echo "Checking PM2 status..."
          pm2 status
          
          echo "Deployment to main completed successfully!"
        EOF
